### PR TITLE
Update base64url dependency version

### PR DESCRIPTION
**Pull request by bwendt-mylo**
Resolves https://nodesecurity.io/advisories/658

### CODE REVIEW

**Comment by omsmith** [comment]
I don't believe maintaining this as a dev dependency raises any flags for installs. Do you have evidence to the contrary?

**Comment by bwendt-mylo** [comment]
No it won't raise any flags for install, but figured it can't hurt to be at the latest version.

**Comment by omsmith** [comment]
Alright, thanks for looking. As you'll note by the test suite, there is much breakage due to new syntax. I'm open to other changes.

**Comment by bwendt-mylo** [comment]
Yeah, looks like it's the use of the default function parameters that's breaking the builds. Probably not worth pursuing at the point.

**Comment by omsmith** [comment]
Going to close for now.

Thanks

**Pull request closed without merging**
