### PR TITLE
Implement RSASSA-PSS (PS) signing and verifying

### PR DESCRIPTION
**Pull request by csprl**
This would be useful for https://github.com/brianloveswords/node-jws/issues/47

### CODE REVIEW

**Comment by omsmith** [comment]
Hi @csprl. Thanks for the contribution.

Would it be possible for you to add some tests to the test suite for this?

**Comment by csprl** [comment]
Hey, I added tests (based on the existing ones for "regular" RSA). It does however seem like support for PSS padding wasn't added until Node.js v6. Function arguments for Verify.verify() were also changed in v7, but back again to the v6 behaviour in v8 which is why the v7 build is failing. Considering these Node.js versions aren't officially supported anymore it might make sense to drop support for them.

**Comment by csprl** [comment]
Sounds good. I added checks for Node version and pinpointed [6.12.0](https://nodejs.org/en/blog/release/v6.12.0/) to be the exact release when PSS support was added. I also added a notice in README.md.

**Comment by omsmith** [comment]
That's awesome, thanks for being so recesponsive to feedback and sorry that I took a while to hop on this!

I'll aim to get this out tonight, but I realized that https://github.com/brianloveswords/node-jwa/pull/26 may have a couple issues with https://github.com/crypto-browserify/browserify-sign that I'll want to address first (perhaps by just reverting my change for now in order to get yours out).

**Comment by csprl** [comment]
No worries at all! You absolutely don't have to rush this change, but getting PS support in node-jws in the near future would be great.

**Comment by nikolaymatrosov** [comment]
It would be great if this PR was merged, so all dependent packages obtain the ability to use PS* algorithms.

**Pull request merged**
